package hendrawd.ganteng.movieinfo.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import hendrawd.ganteng.movieinfo.db.Movie;

import hendrawd.ganteng.movieinfo.db.MovieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieDaoConfig;

    private final MovieDao movieDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieDaoConfig = daoConfigMap.get(MovieDao.class).clone();
        movieDaoConfig.initIdentityScope(type);

        movieDao = new MovieDao(movieDaoConfig, this);

        registerDao(Movie.class, movieDao);
    }
    
    public void clear() {
        movieDaoConfig.getIdentityScope().clear();
    }

    public MovieDao getMovieDao() {
        return movieDao;
    }

}
